# Generated by Django 4.2 on 2025-08-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_submission_task_testcase_submissionrun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionrun',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='task',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubmissionRun',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
