# Generated by Django 4.2 on 2025-08-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_remove_submissionrun_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField(help_text='Template prompt - از {input} برای جایگزینی input استفاده کنید')),
                ('test_cases', models.JSONField(default=list, help_text="فرمت: [{'input': '...', 'expected_output': '...', 'score': 10}]")),
                ('max_score', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(default=300, help_text='زمان اجرا به ثانیه')),
                ('promptfoo_provider', models.CharField(default='openai:gpt-3.5-turbo', help_text='مدل AI برای ارزیابی (مثل openai:gpt-3.5-turbo)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='course.topic')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField(help_text='پرامپت ارسالی کاربر')),
                ('total_score', models.FloatField(default=0)),
                ('max_possible_score', models.IntegerField(default=0)),
                ('test_results', models.JSONField(default=list, help_text='نتایج تفصیلی هر test case')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارزیابی'), ('running', 'در حال ارزیابی'), ('completed', 'تکمیل شده'), ('error', 'خطا در ارزیابی')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('promptfoo_results_file', models.FileField(blank=True, null=True, upload_to='promptfoo_results/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
