# Generated by Django 4.2 on 2025-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_task_usersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=100, help_text='زمان اجرا به ثانیه'),
        ),
    ]
