version: '3.8'

services:
  # MySQL Database (Secured)
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Django Web App
  web:
    build: .
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy with multi-domain support
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Main nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # Site configurations
      - ./nginx/default-server.conf:/etc/nginx/conf.d/default-server.conf
      - ./nginx/main-site.conf:/etc/nginx/conf.d/main-site.conf
      - ./nginx/api-site.conf:/etc/nginx/conf.d/api-site.conf
      - ./nginx/admin-site.conf:/etc/nginx/conf.d/admin-site.conf
      # Static and media files
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
      - phpmyadmin
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # phpMyAdmin for MySQL Database Management (internal access only)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      PMA_HIDE_VERSION: "true"
    # Remove external port - only accessible through nginx proxy
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:
  mysql_data:

networks:
  app-network:
    driver: bridge