# Generated by Django 4.2 on 2025-08-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_task_description_alter_task_time_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
