# Generated by Django 5.2.6 on 2025-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_task_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, null=True, default="", max_length=512),
        ),
    ]
