# Generated by Django 5.2.6 on 2025-09-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_video_video_file_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
